### ISSUE TITLE
複数回使用したスクリプトとトランジション画像のスクリプト一覧への出力について

### ISSUE THREAD

**Issue by karoterra** [Share-aup/.aupExportTool#2]
.aupExportTool v1.0.0 におけるスクリプト一覧の出力について以下の動作が気になりました。

- 複数回使用したスクリプトが使用した回数だけ一覧に出力される
- シーンチェンジで使用したトランジション画像もスクリプト一覧に出力される

これを以下のように修正したコードを書きたいと考えているのですが、このソフトウェアの方針にあっているでしょうか。

- 複数回使用したスクリプトでも一覧には1回だけ出力する
- シーンチェンジで使用したトランジション画像はスクリプト一覧に出力しない

**Comment by chan-mai** [comment]
報告ありがとうございます。
修正したコードについては書いてもらえると有難いです。
宜しくお願い致します。
