### ISSUE TITLE
インストール後において、.Net5のどのバージョンをインストールしなければいけないかが、今一わかりづらい

### ISSUE THREAD

**Issue by kawase19sai** [Share-aup/.aupExportTool#3]
・Windows10環境で、本アプリをインストールするまで、Net5のランタイムを必要としていなかった模様で、インストール後にアプリを実行して、初めてランタイムを必要とするエラーダイアログが表示されましたが、ダイアログから誘導された先のページの、
.Net5ランタイムのバージョンや形態（コンソール版やデスクトップ版、また、x86版か64版か）が多数あり、果たしてどれをインストールするべきかが示されていなかったことに戸惑いを覚えました

※デスクトップ版の64版が自分にとっては正解だった模様ですが、osが32bit版だった場合にはx86版のインストールが要る、ということでしょうか？

**Comment by kawase19sai** [comment]
失礼しました、エラーダイアログの中に、 Desktop って書いてあるところがあったことを思い出しました
が、ダウンロード前に、.Net5ランタイムが必要、という案内があっても良いかなと思った次第です

**Comment by chan-mai** [comment]
.Net5ランタイムに関しては、利用するPCのアーキテクチャに合わせて導入して頂く必要があります。
(例:32bit → x86, 64bit → x86-64)
ダウンロード前の表示については、近日中に配布ページに記載しようと思います。

**Comment by kawase19sai** [comment]
確認いたしました
ありがとうございました
